/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examenlab;

/**
 *
 * @author dell
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgregarPost = new javax.swing.JButton();
        AgregarComment = new javax.swing.JButton();
        AgregarCuenta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        AgregarAmigo = new javax.swing.JButton();
        ViewProfile = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregarPost.setText("Agregar Post");
        AgregarPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPostActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 180, -1));

        AgregarComment.setText("Agregar Comment");
        AgregarComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCommentActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 180, -1));

        AgregarCuenta.setText("Agregar Cuenta");
        AgregarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 180, -1));

        jLabel2.setFont(new java.awt.Font("Gadugi", 0, 36)); // NOI18N
        jLabel2.setText("MENU");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 110, 50));

        AgregarAmigo.setText("Agregar Amigo");
        AgregarAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarAmigoActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarAmigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 180, -1));

        ViewProfile.setText("View Profile");
        ViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProfileActionPerformed(evt);
            }
        });
        getContentPane().add(ViewProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 180, -1));

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPostActionPerformed
        AgregarPost agregarPost= new AgregarPost();
        agregarPost.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AgregarPostActionPerformed

    private void AgregarCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCommentActionPerformed
        AgregarComment agregarComment= new AgregarComment();
        agregarComment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AgregarCommentActionPerformed

    private void AgregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCuentaActionPerformed
        AgregarCuenta agregarCuenta= new AgregarCuenta();
        agregarCuenta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AgregarCuentaActionPerformed

    private void AgregarAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarAmigoActionPerformed
        AgregarAmigo agregarAmigo= new AgregarAmigo();
        agregarAmigo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AgregarAmigoActionPerformed

    private void ViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProfileActionPerformed
        ViewProfile viewProfile= new ViewProfile();
        viewProfile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViewProfileActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarAmigo;
    private javax.swing.JButton AgregarComment;
    private javax.swing.JButton AgregarCuenta;
    private javax.swing.JButton AgregarPost;
    private javax.swing.JButton Salir;
    private javax.swing.JButton ViewProfile;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
